// Code generated by MockGen. DO NOT EDIT.
// Source: tcp-pow/internal/handlers (interfaces: ConnectionMapper)

// Package mocks is a generated GoMock package.
package mocks

import (
	net "net"
	reflect "reflect"
	models "tcp-pow/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockConnectionMapper is a mock of ConnectionMapper interface.
type MockConnectionMapper struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMapperMockRecorder
}

// MockConnectionMapperMockRecorder is the mock recorder for MockConnectionMapper.
type MockConnectionMapperMockRecorder struct {
	mock *MockConnectionMapper
}

// NewMockConnectionMapper creates a new mock instance.
func NewMockConnectionMapper(ctrl *gomock.Controller) *MockConnectionMapper {
	mock := &MockConnectionMapper{ctrl: ctrl}
	mock.recorder = &MockConnectionMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionMapper) EXPECT() *MockConnectionMapperMockRecorder {
	return m.recorder
}

// MapFromInternalData mocks base method.
func (m *MockConnectionMapper) MapFromInternalData(arg0 models.TCPData) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapFromInternalData", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapFromInternalData indicates an expected call of MapFromInternalData.
func (mr *MockConnectionMapperMockRecorder) MapFromInternalData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapFromInternalData", reflect.TypeOf((*MockConnectionMapper)(nil).MapFromInternalData), arg0)
}

// MapToInternalData mocks base method.
func (m *MockConnectionMapper) MapToInternalData(arg0 net.Conn) (models.TCPData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapToInternalData", arg0)
	ret0, _ := ret[0].(models.TCPData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MapToInternalData indicates an expected call of MapToInternalData.
func (mr *MockConnectionMapperMockRecorder) MapToInternalData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapToInternalData", reflect.TypeOf((*MockConnectionMapper)(nil).MapToInternalData), arg0)
}
