// Code generated by MockGen. DO NOT EDIT.
// Source: tcp-pow/internal/handlers (interfaces: ErrorMapper)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "tcp-pow/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockErrorMapper is a mock of ErrorMapper interface.
type MockErrorMapper struct {
	ctrl     *gomock.Controller
	recorder *MockErrorMapperMockRecorder
}

// MockErrorMapperMockRecorder is the mock recorder for MockErrorMapper.
type MockErrorMapperMockRecorder struct {
	mock *MockErrorMapper
}

// NewMockErrorMapper creates a new mock instance.
func NewMockErrorMapper(ctrl *gomock.Controller) *MockErrorMapper {
	mock := &MockErrorMapper{ctrl: ctrl}
	mock.recorder = &MockErrorMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorMapper) EXPECT() *MockErrorMapperMockRecorder {
	return m.recorder
}

// MapToErrorResponse mocks base method.
func (m *MockErrorMapper) MapToErrorResponse(arg0 error) models.TCPData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapToErrorResponse", arg0)
	ret0, _ := ret[0].(models.TCPData)
	return ret0
}

// MapToErrorResponse indicates an expected call of MapToErrorResponse.
func (mr *MockErrorMapperMockRecorder) MapToErrorResponse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapToErrorResponse", reflect.TypeOf((*MockErrorMapper)(nil).MapToErrorResponse), arg0)
}
